import React from 'react';
import { PropTypes } from 'prop-types';
import '../styles/App.css';

class SelectShelf extends React.Component {
	static propTypes = {
		shelf: PropTypes.string,
		changeShelf: PropTypes.func.isRequired
	};

	static defaultProps = {
		shelf: 'none'
	};

	constructor(props) {
		super(props);
		this.handleChange = this.handleChange.bind(this);
	}
	state = {
		currentShelf: this.props.shelf
	}

	/**
	* @description Keeps track of which shelf was selected and
	* triggers function to update shelf
	* @param {object} event - default event generated by onChange
	* @param {string} shelf - which shelf update to
	*/
	handleChange(event) {
		const shelf = event.target.value;
		this.setState({ currentShelf: shelf });
		this.props.changeShelf(shelf);
	}

	render() {
		return (
			<select
				value={this.state.currentShelf}
				onChange={this.handleChange}
			>
				<option disabled>Move to...</option>
				<option value="currentlyReading">Currently Reading</option>
				<option value="wantToRead">Want to Read</option>
				<option value="read">Read</option>
				<option value="none">None</option>
			</select>
		);
	}
}

export { SelectShelf };
