import React from 'react';
import { PropTypes } from 'prop-types';
import { Menu } from 'semantic-ui-react';
import '../styles/App.css';

class SelectShelf extends React.Component {
	static propTypes = {
		shelf: PropTypes.string,
		changeShelf: PropTypes.func.isRequired
	};

	static defaultProps = {
		shelf: 'none'
	};

	state = { currentShelf: this.props.shelf }
	/**
	* @description Keeps track of which shelf was selected and
	* triggers function to update shelf
	* @param {object} e - default event generated by onChange
	* @param {string} name - name of selected shelf
	*/
	handleChange = (e, { name }) => {
		if (name === 'reading') {
			name = 'currentlyReading';
		}
		this.setState({ currentShelf: name });
		this.props.changeShelf(name);
	}

	render() {
		const { currentShelf } = this.state;
		const ItemColor = 'orange';
		return (
			<Menu color='black' vertical compact inverted pointing secondary>
				<Menu.Item name='reading' color={ItemColor} 
					active={currentShelf === 'currentlyReading'} 
					onClick={this.handleChange} 
				/>
				<Menu.Item name='read' color={ItemColor} 
					active={currentShelf === 'read'} 
					onClick={this.handleChange} 
				/>
				<Menu.Item name='wantToRead' color={ItemColor} 
					active={currentShelf === 'wantToRead'} 
					onClick={this.handleChange} 
				/>
				<Menu.Item name='none' color={ItemColor} 
					active={currentShelf === 'none'} 
					onClick={this.handleChange} 
				/>
			</Menu>
		);
	}
}

export { SelectShelf };
